config/routes.rb
Rails.application.routes.draw do
  	devise_for :admins, controllers: {
	  sessions:      'admins/sessions',
	  passwords:     'admins/passwords',
	  registrations: 'admins/registrations'
	}
	devise_for :customers, controllers: {
	  sessions:      'customers/sessions',
	  passwords:     'customers/passwords',
	  registrations: 'customers/registrations'
	}

	get 'about' => 'home#about'

	resources :genres, only: [:index, :create, :edit, :update]
	resources :products
	resources :customers, only: [:index, :show, :edit, :update]

	namespace :user do
		resources :products, only: [:index, :show]
		get 'top' => 'products#top'

		resources :customers, only: [:edit, :update] do
			collection do
				get 'my_page' => 'customers#my_page'
				get 'confirm' => 'customers#confirm'
	        	patch '/withdraw' => 'customers#withdraw'
			end
		end

		resources :shippings, only: [:index, :create, :edit, :update, :destroy]
		resources :cart_items, only: [:index, :create, :update, :destroy] do
			collection do
				delete "destroy_all" => "cart_items#destroy_all"
			end
		end

		resources :orders, only: [:index, :new, :create, :show] do
			collection do
				get 'confirm' => 'orders#confirm'
				get 'complete' => 'orders#complete'
			end
		end
	end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shipping.rb
class Shipping < ApplicationRecord

	belongs_to :customer

	def select_shipping
		[post_code, address, name].join
	end
end

app/models/user.rb
module User
  def self.table_name_prefix
    'user_'
  end
end

app/controllers/user/cart_items_controller.rb
class User::CartItemsController < ApplicationController

	def index
		@cart_items = current_customer.cart_items
	end

	def create
		@cart_item = current_customer.cart_items.new(cart_item_params)
    	@cart_items = current_customer.cart_items
      	if @now_cart_item = current_customer.cart_items.find_by(product_id: @cart_item.product_id)
        	@now_cart_item.amount = @cart_item.amount + @now_cart_item.amount
        	@now_cart_item.update(amount: @now_cart_item.amount)
        	@cart_item.destroy
      	end
    	@cart_item.save
    	redirect_to user_cart_items_path

	end

	def update
		cart_item = CartItem.find(params[:id])
		cart_item.update(cart_item_params)
		redirect_to user_cart_items_path
	end

	def destroy
		cart_item = CartItem.find(params[:id])
		cart_item.destroy
		redirect_to user_cart_items_path
	end

	def destroy_all
		CartItem.destroy_all
    	redirect_to user_products_path
	end

	private
	def cart_item_params
		params.require(:cart_item).permit(:amount, :customer_id, :product_id)
	end
end

app/controllers/user/customers_controller.rb
class User::CustomersController < ApplicationController


	def my_page
		@customer = current_customer
	end

	def edit
		@customer = current_customer
	end

	def update
	end

	def confirm
	end

	def withdraw
	end

	private
	def customer_params
		params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :phone_number, :address, :is_deleted)
	end
end

app/controllers/user/orders_controller.rb
class User::OrdersController < ApplicationController


	def index
	end

	def new
		@order = Order.new
	end

	def create
	end

	def show
	end

	def confirm
	end

	def complete
	end

	private
	def order_params
		params.require(:order).permit(:post_code, :address, :name, :total_price, :shipping_cost, :payment, :status, :customer_id)
	end
end

app/controllers/user/products_controller.rb
class User::ProductsController < ApplicationController

	before_action :tax_price, only: [:show]


	def top
		@genres = Genre.all
		@products = Product.order("RANDOM()").all
	end


	def index
		@genres = Genre.all
		if params[:genre_id]
			@genre = Genre.find(params[:genre_id])
			@products = Product.where("genre_id LIKE?", "#{@genre.id}")
		else
			@products = Product.all
		end
	end

	def show
		@genres = Genre.all
		@product = Product.find(params[:id])
		@cart_item = CartItem.new
	end

	private

	def tax_price
		tax = 0.1
		@product = Product.find(params[:id])
		@tax_price = @product.price * tax
		@tax_price = @product.price + @tax_price
	end

end

app/controllers/user/shippings_controller.rb
class User::ShippingsController < ApplicationController

	def index
		@shipping = Shipping.new
		@shippings = Shipping.all
	end

	def create
		shipping = current_customer.shippings.new(shipping_params)
		shipping.save
		redirect_to user_shippings_path
	end

	def edit
		@shipping = Shipping.find(params[:id])
	end

	def update
		shipping = Shipping.find(params[:id])
		shipping.update(shipping_params)
		redirect_to user_shippings_path
	end

	def destroy
		shipping = current_customer.shippings.find_by(params[:shipping_id])
		shipping.destroy
		redirect_to user_shippings_path
	end

	private
	def shipping_params
		params.require(:shipping).permit(:name, :address, :post_code)
	end
end

app/helpers/user/cart_items_helper.rb
module User::CartItemsHelper
end

app/helpers/user/customers_helper.rb
module User::CustomersHelper
end

app/helpers/user/orders_helper.rb
module User::OrdersHelper
end

app/helpers/user/products_helper.rb
module User::ProductsHelper
end

app/helpers/user/shippings_helper.rb
module User::ShippingsHelper
end

app/views/user/shippings/edit.html.erb
<div class="row">
	<h2>配送先を編集する</h2>
	<%= form_with model: @shipping, url: user_shipping_path(@shipping) do |f| %>
		<div class="form-group">
			<%= f.label :post_code, '郵便番号（ハイフンなし）', class: 'col-xs-3' %>
			<%= f.text_field :post_code %>
		</div>
		<div class="form-group">
			<%= f.label :address, '住所', class: 'col-xs-3' %>
			<%= f.text_field :address %>
		</div>
		<div class="form-group">
			<%= f.label :name, '宛名', class: 'col-xs-3' %>
			<%= f.text_field :name %>
		</div>
		<%= f.submit '編集する', class: 'btn btn-primary col-xs-offset-9' %>
	<% end %>
</div>

app/views/user/shippings/index.html.erb
<div class="row">
	<h2>配送先一覧/登録</h2>
	<%= form_with model: @shipping, url: user_shippings_path do |f| %>
		<div class="form-group">
			<%= f.label :post_code, '郵便番号（ハイフンなし）', class: 'col-xs-3' %>
			<%= f.text_field :post_code %>
		</div>
		<div class="form-group">
			<%= f.label :address, '住所', class: 'col-xs-3' %>
			<%= f.text_field :address %>
		</div>
		<div class="form-group">
			<%= f.label :name, '宛名', class: 'col-xs-3' %>
			<%= f.text_field :name %>
		</div>
		<%= f.submit '登録', class: 'btn btn-success col-xs-offset-9' %>
	<% end %>

	<table class="table">
		<thead>
			<tr>
				<th>郵便番号</th>
				<th>住所</th>
				<th>宛名</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			<% @shippings.each do |shipping| %>
			<tr>
				<td><%= shipping.post_code %></td>
				<td><%= shipping.address %></td>
				<td><%= shipping.name %></td>
				<td>
					<%= link_to '編集', edit_user_shipping_path(shipping), class: 'btn btn-primary' %>
					<%= link_to '削除', user_shipping_path(shipping), method: :delete, class: 'btn btn-danger' %>
				</td>
			</tr>
			<% end %>
		</tbody>
	</table>
</div>